--CREATE TABLE users (
--    username  VARCHAR(255) PRIMARY KEY,
--    password  VARCHAR(255) NOT NULL,
--    enabled   BOOLEAN      NOT NULL,
--    email     VARCHAR(255),
--    phone     INTEGER
--);

--CREATE TABLE authorities (
--    username VARCHAR(255) NOT NULL,
--    authority VARCHAR(50) NOT NULL,
--    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users(username),
--    UNIQUE (username, authority)
--);
